# ============================================
# General Options
# ============================================

# --- Terminal ---
set -g default-terminal "tmux-256color"
set -ga terminal-features ",xterm-256color:RGB"

# --- Basic Behavior ---
set -g mouse on
set -g history-limit 500000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g set-clipboard on
set -g allow-passthrough on
set -ga terminal-overrides ',*:Smulx=\E[4::%p1%dm' # undercurl support
set -ga terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m' # undercurl colors
set -g focus-events on
set -g display-time 3000

# --- Vi Mode ---
setw -g mode-keys vi
set -g status-keys vi

# --- Responsiveness ---
set -sg escape-time 0
set -g repeat-time 600
