---@type LazySpec
return {
  "AstroNvim/astroui",
  ---@type AstroUIOpts
  opts = {
    status = {
      colors = {
        bg = "NONE",
        section_bg = "NONE",
        mode_fg = "#ADB0BB",
        mode_bg = "NONE",
        normal = "NONE",
        insert = "NONE",
        visual = "NONE",
        replace = "NONE",
        command = "NONE",
        terminal = "NONE",
        inactive = "NONE",
      },
    },
    highlights = {
      init = {
        Normal = { bg = "NONE" },
        NormalNC = { bg = "NONE" },
        NormalFloat = { bg = "NONE" },
        SignColumn = { bg = "NONE" },
        EndOfBuffer = { bg = "NONE" },
        WinBar = { bg = "NONE" },
        WinBarNC = { bg = "NONE" },
        WinSeparator = { bg = "NONE" },
        VertSplit = { bg = "NONE" },
        StatusLine = { bg = "NONE" },
        StatusLineNC = { bg = "NONE" },
        TabLine = { bg = "NONE" },
        TabLineFill = { bg = "NONE" },
        TabLineSel = { bg = "NONE" },
        CursorLine = { bg = "NONE" },
        Folded = { bg = "NONE" },
        FoldColumn = { bg = "NONE" },
        NeoTreeNormal = { bg = "NONE" },
        NeoTreeNormalNC = { bg = "NONE" },
        NeoTreeEndOfBuffer = { bg = "NONE" },
        NeoTreeWinSeparator = { bg = "NONE" },
        NeoTreeVertSplit = { bg = "NONE" },
        NeoTreeStatusLine = { bg = "NONE" },
        NeoTreeStatusLineNC = { bg = "NONE" },
        NeoTreeTabActive = { bg = "NONE" },
        NeoTreeTabInactive = { bg = "NONE" },
        NeoTreeTabSeparatorActive = { bg = "NONE" },
        NeoTreeTabSeparatorInactive = { bg = "NONE" },
        NeoTreeTitleBar = { bg = "NONE" },
        NeoTreeCursorLine = { bg = "NONE" },
        NeoTreeFloatBorder = { bg = "NONE" },
        NeoTreeFloatTitle = { bg = "NONE" },
        NeoTreeSignColumn = { bg = "NONE" },
      },
    },
  },
}
